### ISSUE TITLE
invalid ELF header

### ISSUE THREAD

**Issue by Mohannadcse** [ldklab/scored23_release#2]
I received this error after running `python3 ASTLooper.py /nobackup/scored23_release/ASTanalysis/Dataset /nobackup/scored23_release/Processed`

```
Traceback (most recent call last):
  File "/nobackup/scored23_release/ASTanalysis/ASTParser.py", line 381, in <module>
    main()
  File "/nobackup/scored23_release/ASTanalysis/ASTParser.py", line 291, in main
    CPP_LANGUAGE = Language("build/my-languages.so", "cpp")
  File "/nobackup/scored23_release/.venv/lib/python3.10/site-packages/tree_sitter/__init__.py", line 105, in __init__
    self.lib = cdll.LoadLibrary(library_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: build/my-languages.so: invalid ELF header
```

**Comment by ldk-linux** [comment]
I think the repo may have the pre-compiled tree-sitter parser library for MacOS, and you are attempting to run the tool on Linux. The instructions to build a parser appropriate for your machine/OS are here: https://github.com/tree-sitter/py-tree-sitter (you need to build tree-sitter-cpp and replace the my-language.so file with the one you created).

@s-bukhari once you get the chance can you update the README with instructions on how to build tree-sitter on one's machine?

**Comment by Mohannadcse** [comment]
I listed in [requirements.txt](https://github.com/ldklab/scored23_release/blob/main/requirements.txt#L16) the package `tree_sitter`. I think you are talking about `build/my-languages.so`, that the current version in the repo is for MacOS, and I need to replace it with the Linux version. I inspected the .so file using `file ASTanalysis/build/my-languages.so ` and it's for MacOS.
```
ASTanalysis/build/my-languages.so: Mach-O 64-bit arm64 dynamically linked shared library, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|WEAK_DEFINES|BINDS_TO_WEAK|NO_REEXPORTED_DYLIBS>
```

I'll be waiting for the instructions/tips from @s-bukhari to setup this .so lib for Ubuntu. Thx

**Comment by s-bukhari** [comment]
Prereqs:
- Delete the existing "build" folder if not on MacOS

Steps to generate "my-language.so" / install Tree-Sitter
(steps are available at [https://github.com/tree-sitter/py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter))
- To install tree-sitter run the below command on your terminal:
`pip3 install tree_sitter`

- Create a folder named "vendor" within the root folder "ASTanalysis" and then git clone the tree-sitter library in it.
`git clone https://github.com/tree-sitter/tree-sitter-python`

- run the "builder.py" file that already exists in the root "ASTanalysis" folder
`python builder.py`
- this will create a new "build" folder with the new "my-language.so" file.

**Comment by Mohannadcse** [comment]
The `builder.py` is looking for `vendor/tree-sitter-cpp` while the created folder after the clone is `vendor/tree-sitter-python/`. SO do I need only to change the directory name ? or do I need to checkout a specific branch?

Because `builder.py` has locations for `CPP` and `python`:
```[
        "vendor/tree-sitter-cpp"
        # 'vendor/tree-sitter-python'
    ],
``` 

PS: I already added `tree_sitter` to the requirements.txt, so there is no need for the pip.

**Comment by s-bukhari** [comment]
You have to checkout the CPP branch. 

please clone:
`git clone https://github.com/tree-sitter/tree-sitter-cpp`

**Comment by Mohannadcse** [comment]
this step works now, addressed in the PR https://github.com/ldklab/scored23_release/pull/3
